/**
 * @brief	Header file for c array generated by lcd-image-converter.
 * 			Project's home page: http://www.riuson.com/lcd-image-converter 
 */

#ifndef _TYPE_IMAGE_H
#define _TYPE_IMAGE_H

#if defined(__cplusplus)
extern "C" {     /* Make sure we have C-declarations in C++ programs */
#endif

#include <stdint.h>

typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
	 
#ifdef __cplusplus
}
#endif	 

#endif

